### PR TITLE
Enable dependabot version updates for actions

### PR DESCRIPTION
**Pull request by avdv**

### CODE REVIEW

**Comment by avdv** [comment]
Unfortunately, dependabot will only update stuff in `.github/workflows` and not touch `.github/actions`.

Also, this repository seems to be prepared for using renovate instead since it uses pinned actions:
```
uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
```

I'll replace the dependabot config with renovate.

**Comment by YorikSar** [comment]
You can set dependabot up to update `.github/actions` by adding another section pointing to it in `directory:` field. I don't really know if renovate is better than dependabot though.

**Comment by avdv** [comment]
> You can set dependabot up to update `.github/actions` by adding another section pointing to it in `directory:` field.

Oh, really? Since it is set to `/` currently which will make it look into `.github/workflows`, so I assume you could only specify a different directory with the same structure?

> I don't really know if renovate is better than dependabot though.

At least it also works for Bazel, and pinning Github actions by SHA digest is also nice.

**Comment by YorikSar** [comment]
> Oh, really? Since it is set to `/` currently which will make it look into `.github/workflows`, so I assume you could only specify a different directory with the same structure?

It’s a bit weird in assuming that `/` means `.github/workflows`. It’s working for organist, for example: https://github.com/nickel-lang/organist/blob/main/.github/dependabot.yml

**Comment by avdv** [comment]
> It’s a bit weird in assuming that `/` means `.github/workflows`. It’s working for organist, for example: [nickel-lang/organist@`main`/.github/dependabot.yml](https://github.com/nickel-lang/organist/blob/main/.github/dependabot.yml?rgh-link-date=2024-11-14T13%3A30%3A25Z)

Oh yes, that is weird indeed. TIL

But let's try https://github.com/tweag/run-nix-shell/pull/13 ;-)

**Pull request merged**
