### PR TITLE
Replace dependabot with renovate

### PR DESCRIPTION
**Pull request by avdv**
- **Remove dependabot**
- **Add renovate config**

This should properly take care of github action and Bazel dependency updates.

### CODE REVIEW

**Review by YorikSar — APPROVED** [review]
I've also added renovate to this repo on org level. Let's see if this works.

**Comment by YorikSar** [comment]
I'm not sure where to do this. It's in the list in the app config on GitHub:
image
Do I need to register in Renovate itself?.. Do you know who did this for other repos?

**Comment by avdv** [comment]
> Do I need to register in Renovate itself?.. 

Since they have two different apps, you need to decide which one you want: either the forking app or the app that creates PRs in the repo itself (I am using that one usually).

So, go to https://developer.mend.io/ , select "Renovate app" and go to the org, select the repo and acitvate it in the settings.

> Do you know who did this for other repos?

Yes. I did. But one needs admin access to the repositories and thus I cannot do it here.

**Comment by YorikSar** [comment]
I really don't like giving third parties admin access to repositories... Why does it need admin access? Can I do necessary settings myself?

**Comment by YorikSar** [comment]
Ugh... It seems I was stuck on "registration" screen that wasn't really registering anything, just asking to agree to their ToS. I've enabled this repo and it started doing something.
I would really prefer to have own renovate job somewhere: either in this repo, on in our infra.

**Comment by avdv** [comment]
> I really don't like giving third parties admin access to repositories... Why does it need admin access?

I don't think it needs admin access to the repo. AFAIU, it checks if the user has admin access to the repo before it allows to configure the app.

https://docs.renovatebot.com/security-and-permissions/#permissions

> Can I do necessary settings myself?

I think you can only control the app settings in the app.

**Comment by avdv** [comment]
> I would really prefer to have own renovate job somewhere: either in this repo, on in our infra.

:smile: we migrate away from self-hosted renovate to the app. but I would happily switch back.

**Comment by YorikSar** [comment]
> 😄 we migrate away from self-hosted renovate to the app. but I would happily switch back.

Why? Is something missing in self-hosted version?

**Comment by avdv** [comment]
> Why? Is something missing in self-hosted version?

See https://github.com/tweag/scalable-builds-group/issues/133

**Comment by YorikSar** [comment]
Huh. I guess, I didn't notice that. It seems the only issue is with PAT and that can be avoided by creating own app and generating a token from its key as described in https://github.com/renovatebot/github-action?tab=readme-ov-file#example-with-github-app. I also see renovate [module](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/renovate.nix) in NixOS unstable, so we could run it on our infra even without GHA :)

**Pull request merged**
